[build]
  publish   = "."           # statické soubory v kořeni
  functions = "functions"

[[redirects]]
  from   = "/go"
  to     = "/.netlify/functions/redirect"
  status = 302
  force  = true
  conditions = { Method = ["POST"] }   # GET se nepošle ⇒ crawler zůstane
